spring.application.name=application
server.port=8080
spring.jackson.serialization.indent-output=true
logging.level.org.springframework.web=DEBUG

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
# SQL
spring.jpa.show-sql=true
# SQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# MongoDB
spring.mongodb.uri = mongodb://localhost:27017/shop_db

# Внешний сервис юр.лиц (POST/GET проксируются сюда + /jur)
app.external.jur.base-url=http://localhost:8089